### ISSUE TITLE
Latest Firmware changes 4 byte Prefix

### ISSUE THREAD

**Issue by mkillock** [EgoManiac/TPlink-PoSH#1]
if anyone runs the firmware upgrade to the H110, then I found that the only thing that's changed is the four byte prefix, so the following change in Encode-ForTPLink fixes the script

    for($i = 0; $i -lt 3;$i++){

        write-output 0

    }
        Write-Output 42

**Comment by EgoManiac** [comment]
thanks for letting me know... I have updated the code to reflect
